[package]
name = "gba_example"
version = "0.1.0"
edition = "2024"
publish = false

[profile.dev]
opt-level = 3
debug = true

[profile.release]
lto = true

[dependencies]
gba = "0.15.0"
gba_mobile = {path = "../../gba_mobile"}
log = "0.4.29"
mgba_log = "0.2.1"
